variables:
    PRIVATE_TOKEN: 'WbccpUnpG2yiFZptHDCB'
    PLUGIN_NAME : 'AuthorDOIScreeningPlugin'

stages:
    - release
    
build_plugin:
    stage: release
    only:
        - tags
    script:
        - mkdir ${PLUGIN_NAME}
        - cp -r * ${PLUGIN_NAME}
        - tar -zcvf ${PLUGIN_NAME}.tar.gz ${PLUGIN_NAME}
        - "echo \" 'bla: ${PRIVATE_TOKEN}' \""
        - "content=$(curl --request POST --header 'Private-Token: \'${PRIVATE_TOKEN}'\' --form 'file=@./${PLUGIN_NAME}.tar.gz' 'https://gitlab.lepidus.com.br/api/v4/projects/\'${CI_PROJECT_ID}'/uploads')"
        - url=$(jq -r '.url' <<<$content)
        - absolute_url=${CI_PROJECT_URL}${url}
        - "response=$(curl --header 'Content-Type: application/json' --header \"PRIVATE-TOKEN: $PRIVATE_TOKEN\" --data '{ \"name\": \"\'$CI_COMMIT_TAG\'\", \"tag_name\": \"\'$CI_COMMIT_TAG\'\", \"description\": \"\" , \"assets\": { \"links\": [{ \"name\": \"${PLUGIN_NAME}\", \"url\": \"\'$absolute_url\'\" }] } }' --request POST https://gitlab.lepidus.com.br/api/v4/projects/$CI_PROJECT_ID/releases)"
        - "rm -rf ${PLUGIN_NAME}"